comment:
  require_changes: "coverage_drop OR uncovered_patch"

# coverage:
#   status:
#     project: off
#     patch: off

ignore:
  - "**/test_*.py  # ignore any files at any depth that start with 'test_' and end with '.py'